# Generated by Django 5.0.6 on 2024-06-17 20:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
