# Generated by Django 5.0.6 on 2026-08-30 09:57

import datetime
import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadTripDayPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Číslo dne",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Datum"),
                ),
                ("intro", models.CharField(max_length=300, verbose_name="Krátký úvod")),
                ("body", wagtail.fields.RichTextField(verbose_name="Zápis z cesty")),
            ],
            options={
                "verbose_name": "Den autovandru",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="RoadTripDayGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Popisek"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="roadtrips.roadtripdaypage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoadTripIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Autovandry",
                        help_text="Krátký název zobrazovaný v hlavním menu.",
                        max_length=20,
                        verbose_name="Podtitulek v menu",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Úvod"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Titulní obrázek sekce, ideálně na šířku (1000 až 3000 px).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rozcestník autovandrů",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="RoadTripPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Začátek cesty"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Konec cesty"
                    ),
                ),
                ("intro", models.CharField(max_length=300, verbose_name="Krátký úvod")),
                ("body", wagtail.fields.RichTextField(verbose_name="Popis celé cesty")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Titulní obrázek cesty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autovandr",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="RoadTripGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Popisek"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="roadtrips.roadtrippage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
