# Generated by Django 5.0.6 on 2026-08-30 10:07

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadtripdaypage",
            name="mapy_photos",
            field=wagtail.fields.StreamField(
                [
                    (
                        "mapy_photo",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image_url",
                                    wagtail.blocks.URLBlock(label="URL obrázku"),
                                ),
                                (
                                    "mapy_url",
                                    wagtail.blocks.URLBlock(label="Odkaz na Mapy.com"),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Fotografie z Mapy.com",
            ),
        ),
        migrations.AddField(
            model_name="roadtrippage",
            name="mapy_photos",
            field=wagtail.fields.StreamField(
                [
                    (
                        "mapy_photo",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image_url",
                                    wagtail.blocks.URLBlock(label="URL obrázku"),
                                ),
                                (
                                    "mapy_url",
                                    wagtail.blocks.URLBlock(label="Odkaz na Mapy.com"),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="Fotografie z Mapy.com",
            ),
        ),
    ]
