# Generated by Django 5.0.6 on 2026-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0002_roadtripdaypage_mapy_photos_roadtrippage_mapy_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadtripdaypage",
            name="mapy_route_url",
            field=models.URLField(
                blank=True,
                help_text="Vložte pouze sdílecí URL mapy, například https://mapy.com/s/hodepofuza. Náhled se vytvoří automaticky.",
                verbose_name="Mapa trasy na Mapy.com",
            ),
        ),
        migrations.AddField(
            model_name="roadtrippage",
            name="mapy_route_url",
            field=models.URLField(
                blank=True,
                help_text="Vložte pouze sdílecí URL mapy, například https://mapy.com/s/hodepofuza. Náhled se vytvoří automaticky.",
                verbose_name="Mapa trasy na Mapy.com",
            ),
        ),
    ]
