# Generated by Django 5.0.6 on 2026-08-30 13:57

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


def content_blocks():
    return [
        (
            "text",
            wagtail.blocks.RichTextBlock(
                icon="pilcrow",
                label="Text",
                template="blocks/paragraph_block.html",
            ),
        ),
        (
            "mapy_photo",
            wagtail.blocks.StructBlock(
                [
                    ("image_url", wagtail.blocks.URLBlock(label="URL obrázku")),
                    ("mapy_url", wagtail.blocks.URLBlock(label="Odkaz na Mapy.com")),
                    (
                        "caption",
                        wagtail.blocks.CharBlock(label="Popisek", required=False),
                    ),
                ]
            ),
        ),
        (
            "image",
            wagtail.blocks.StructBlock(
                [
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            label="Obrázek", required=True
                        ),
                    ),
                    (
                        "caption",
                        wagtail.blocks.CharBlock(label="Popisek", required=False),
                    ),
                    (
                        "attribution",
                        wagtail.blocks.CharBlock(label="Zdroj", required=False),
                    ),
                ]
            ),
        ),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0003_roadtripdaypage_mapy_route_url_and_more"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadtripdaypage",
            name="content",
            field=wagtail.fields.StreamField(
                content_blocks(),
                blank=True,
                help_text=(
                    "Libovolně střídejte texty, fotografie z Mapy.com a vlastní "
                    "obrázky."
                ),
                verbose_name="Řaditelný obsah",
            ),
        ),
        migrations.AddField(
            model_name="roadtripdaypage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Titulní obrázek dne",
            ),
        ),
        migrations.AddField(
            model_name="roadtrippage",
            name="content",
            field=wagtail.fields.StreamField(
                content_blocks(),
                blank=True,
                help_text=(
                    "Libovolně střídejte texty, fotografie z Mapy.com a vlastní "
                    "obrázky."
                ),
                verbose_name="Řaditelný obsah",
            ),
        ),
    ]
