# Generated by Django 5.0.6 on 2026-08-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0005_migrate_legacy_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roadtripgalleryimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="roadtripgalleryimage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="roadtripdaypage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="roadtripdaypage",
            name="mapy_photos",
        ),
        migrations.RemoveField(
            model_name="roadtrippage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="roadtrippage",
            name="mapy_photos",
        ),
        migrations.DeleteModel(
            name="RoadTripDayGalleryImage",
        ),
        migrations.DeleteModel(
            name="RoadTripGalleryImage",
        ),
    ]
