# Generated by Django 5.0.6 on 2026-08-30 14:07

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0006_remove_roadtripgalleryimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadtripdaypage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.blocks.RichTextBlock(
                            icon="pilcrow",
                            label="Text",
                            template="blocks/paragraph_block.html",
                        ),
                    ),
                    (
                        "mapy_photo",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image_url",
                                    wagtail.blocks.URLBlock(label="URL obrázku"),
                                ),
                                (
                                    "mapy_url",
                                    wagtail.blocks.URLBlock(label="Odkaz na Mapy.com"),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Obrázek", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(
                                        label="Zdroj", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        help_text="Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                                        label="Video",
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                help_text="Libovolně střídejte texty, fotografie z Mapy.com a vlastní obrázky.",
                verbose_name="Řaditelný obsah",
            ),
        ),
        migrations.AlterField(
            model_name="roadtrippage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.blocks.RichTextBlock(
                            icon="pilcrow",
                            label="Text",
                            template="blocks/paragraph_block.html",
                        ),
                    ),
                    (
                        "mapy_photo",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image_url",
                                    wagtail.blocks.URLBlock(label="URL obrázku"),
                                ),
                                (
                                    "mapy_url",
                                    wagtail.blocks.URLBlock(label="Odkaz na Mapy.com"),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Obrázek", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(
                                        label="Zdroj", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        help_text="Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                                        label="Video",
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                help_text="Libovolně střídejte texty, fotografie z Mapy.com a vlastní obrázky.",
                verbose_name="Řaditelný obsah",
            ),
        ),
    ]
