# Generated by Django 5.0.6 on 2026-08-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0007_alter_roadtripdaypage_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadtripdaypage",
            name="image_heading",
            field=models.CharField(
                blank=True,
                help_text="Volitelný nadpis zobrazený nad titulní fotografií.",
                max_length=150,
                verbose_name="Nadpis titulní fotografie",
            ),
        ),
        migrations.AddField(
            model_name="roadtrippage",
            name="image_heading",
            field=models.CharField(
                blank=True,
                help_text="Volitelný nadpis zobrazený nad titulní fotografií.",
                max_length=150,
                verbose_name="Nadpis titulní fotografie",
            ),
        ),
    ]
