# Generated by Django 5.0.6 on 2026-09-04 19:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0008_roadtripdaypage_image_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadtripdaypage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("mapy_photo", 4), ("image", 8), ("video", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    1: ("wagtail.blocks.URLBlock", (), {"label": "URL obrázku"}),
                    2: ("wagtail.blocks.URLBlock", (), {"label": "Odkaz na Mapy.com"}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Popisek", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image_url", 1), ("mapy_url", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Obrázek", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Zdroj", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Volitelná cílová adresa obrázku, například sdílecí odkaz https://mapy.com/s/hejunakope.",
                            "label": "Odkaz po kliknutí",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("caption", 3),
                                ("attribution", 6),
                                ("link_url", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                            "label": "Video",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 9), ("caption", 3)]],
                        {},
                    ),
                },
                help_text="Libovolně střídejte texty, fotografie z Mapy.com a vlastní obrázky.",
                verbose_name="Řaditelný obsah",
            ),
        ),
        migrations.AlterField(
            model_name="roadtrippage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("mapy_photo", 4), ("image", 8), ("video", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    1: ("wagtail.blocks.URLBlock", (), {"label": "URL obrázku"}),
                    2: ("wagtail.blocks.URLBlock", (), {"label": "Odkaz na Mapy.com"}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Popisek", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image_url", 1), ("mapy_url", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Obrázek", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Zdroj", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Volitelná cílová adresa obrázku, například sdílecí odkaz https://mapy.com/s/hejunakope.",
                            "label": "Odkaz po kliknutí",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("caption", 3),
                                ("attribution", 6),
                                ("link_url", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                            "label": "Video",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 9), ("caption", 3)]],
                        {},
                    ),
                },
                help_text="Libovolně střídejte texty, fotografie z Mapy.com a vlastní obrázky.",
                verbose_name="Řaditelný obsah",
            ),
        ),
    ]
