# Generated by Django 5.0.6 on 2026-09-05 08:24

import json

import wagtail.fields
from django.db import migrations


def remove_block(value):
    """Odstraní bloky mapy_photo a zachová formát uloženého StreamFieldu."""
    stored_as_string = isinstance(value, str)

    if stored_as_string:
        try:
            blocks = json.loads(value)
        except (TypeError, ValueError):
            return value
    else:
        blocks = getattr(value, "raw_data", value)

    if not isinstance(blocks, list):
        return value

    filtered_blocks = [
        block
        for block in blocks
        if not isinstance(block, dict) or block.get("type") != "mapy_photo"
    ]

    if stored_as_string:
        return json.dumps(filtered_blocks)
    return filtered_blocks


def remove_mapy_photo_blocks(apps, schema_editor):
    RoadTripPage = apps.get_model("roadtrips", "RoadTripPage")
    RoadTripDayPage = apps.get_model("roadtrips", "RoadTripDayPage")
    Revision = apps.get_model("wagtailcore", "Revision")

    for page_model in (RoadTripPage, RoadTripDayPage):
        for page in page_model.objects.all().iterator():
            page.content = remove_block(page.content)
            page.save(update_fields=["content"])

    revisions = Revision.objects.filter(
        content_type__app_label="roadtrips",
        content_type__model__in=("roadtrippage", "roadtripdaypage"),
    )
    for revision in revisions.iterator():
        data = revision.content
        if not isinstance(data, dict) or "content" not in data:
            continue

        data["content"] = remove_block(data["content"])
        revision.content = data
        revision.save(update_fields=["content"])


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0009_alter_roadtripdaypage_content_and_more"),
    ]

    operations = [
        migrations.RunPython(
            remove_mapy_photo_blocks,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="roadtripdaypage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 5), ("video", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Obrázek", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Popisek", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Zdroj", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Volitelná cílová adresa obrázku, například sdílecí odkaz https://mapy.com/s/hejunakope.",
                            "label": "Odkaz po kliknutí",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("caption", 2),
                                ("attribution", 3),
                                ("link_url", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                            "label": "Video",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 6), ("caption", 2)]],
                        {},
                    ),
                },
                help_text="Libovolně střídejte texty, vlastní obrázky a vlastní videa.",
                verbose_name="Řaditelný obsah",
            ),
        ),
        migrations.AlterField(
            model_name="roadtrippage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 5), ("video", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Obrázek", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Popisek", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Zdroj", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Volitelná cílová adresa obrázku, například sdílecí odkaz https://mapy.com/s/hejunakope.",
                            "label": "Odkaz po kliknutí",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("caption", 2),
                                ("attribution", 3),
                                ("link_url", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                            "label": "Video",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 6), ("caption", 2)]],
                        {},
                    ),
                },
                help_text="Libovolně střídejte texty, vlastní obrázky a vlastní videa.",
                verbose_name="Řaditelný obsah",
            ),
        ),
    ]
