# Generated by Django 5.0.6 on 2026-09-05 09:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0010_alter_roadtripdaypage_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadtripdaypage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 5), ("video", 7), ("day_summary", 20)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Obrázek", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Popisek", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Zdroj", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Volitelná cílová adresa obrázku, například sdílecí odkaz https://mapy.com/s/hejunakope.",
                            "label": "Odkaz po kliknutí",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("caption", 2),
                                ("attribution", 3),
                                ("link_url", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                            "label": "Video",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 6), ("caption", 2)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Přehled dne", "label": "Nadpis"},
                    ),
                    9: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {
                            "decimal_places": 1,
                            "help_text": "Vzdálenost za tento den. Pro den bez přejezdu zadejte 0.",
                            "label": "Ujeté kilometry",
                            "max_digits": 7,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"label": "Země"}),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "default": [],
                            "help_text": "Přidejte země v pořadí, ve kterém jste jimi projížděli.",
                            "label": "Navštívené země",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Například Praha → Drážďany → Berlín.",
                            "label": "Trasa",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Například 4 h 30 min.",
                            "label": "Čas na cestě",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Místo noclehu", "required": False},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"label": "Název údaje"}),
                    16: ("wagtail.blocks.CharBlock", (), {"label": "Hodnota"}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 15), ("value", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {
                            "default": [],
                            "help_text": "Například Počasí: Slunečno, 24 °C nebo Pěšky: 8 km.",
                            "label": "Další údaje",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Poznámka", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 8),
                                ("distance_km", 9),
                                ("countries", 11),
                                ("route", 12),
                                ("driving_time", 13),
                                ("overnight_stay", 14),
                                ("extra_items", 18),
                                ("note", 19),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Libovolně střídejte texty, vlastní obrázky a vlastní videa. Na konec zápisu můžete přidat blok Přehled dne.",
                verbose_name="Řaditelný obsah",
            ),
        ),
    ]
