# Generated by Django 5.0.6 on 2026-09-05 16:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0016_add_trip_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadtripdaypage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 5), ("video", 7), ("day_summary", 22)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Obrázek", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Popisek", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Zdroj", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Volitelná cílová adresa obrázku, například sdílecí odkaz https://mapy.com/s/hejunakope.",
                            "label": "Odkaz po kliknutí",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("caption", 2),
                                ("attribution", 3),
                                ("link_url", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                            "label": "Video",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 6), ("caption", 2)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Přehled dne", "label": "Nadpis"},
                    ),
                    9: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {
                            "decimal_places": 1,
                            "help_text": "Celkem od začátku této cesty ke konci dne. Kilometry za den se vypočítají odečtením celkového stavu předchozího dne; první den počítá od nuly. Bez celkového stavu předchozího dne se denní vzdálenost nezobrazí.",
                            "label": "Celkové najeté kilometry",
                            "max_digits": 7,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"label": "Země"}),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "default": [],
                            "help_text": "Přidejte země v pořadí, ve kterém jste jimi projížděli.",
                            "label": "Navštívené země",
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"label": "Moře"}),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "default": [],
                            "help_text": "Přidejte moře v pořadí, ve kterém jste je navštívili.",
                            "label": "Navštívená moře",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Například :home: → Drážďany → Berlín. Zápis :home: zobrazí ikonu domova.",
                            "label": "Trasa",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Například 4 h 30 min.",
                            "label": "Čas na cestě",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Místo noclehu", "required": False},
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"label": "Název údaje"}),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "Hodnota"}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 17), ("value", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ListBlock",
                        (19,),
                        {
                            "default": [],
                            "help_text": "Například Počasí: Slunečno, 24 °C nebo Pěšky: 8 km.",
                            "label": "Další údaje",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Poznámka", "required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 8),
                                ("total_distance_km", 9),
                                ("countries", 11),
                                ("seas", 13),
                                ("route", 14),
                                ("driving_time", 15),
                                ("overnight_stay", 16),
                                ("extra_items", 20),
                                ("note", 21),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Libovolně střídejte texty, vlastní obrázky a vlastní videa. Na konec zápisu můžete přidat blok Přehled dne.",
                verbose_name="Řaditelný obsah",
            ),
        ),
        migrations.AlterField(
            model_name="roadtrippage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 5), ("video", 7), ("trip_summary", 16)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Obrázek", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Popisek", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Zdroj", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Volitelná cílová adresa obrázku, například sdílecí odkaz https://mapy.com/s/hejunakope.",
                            "label": "Odkaz po kliknutí",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("caption", 2),
                                ("attribution", 3),
                                ("link_url", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                            "label": "Video",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 6), ("caption", 2)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Přehled autovandru", "label": "Nadpis"},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Například :home: → Oslo → :home:. Zápis :home: zobrazí ikonu domova.",
                            "label": "Trasa",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Například 32 h.",
                            "label": "Čas na cestě",
                            "required": False,
                        },
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {"label": "Název údaje"}),
                    12: ("wagtail.blocks.CharBlock", (), {"label": "Hodnota"}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 11), ("value", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {
                            "default": [],
                            "help_text": "Například Pěšky: 60 km nebo Trajekty: 3 plavby.",
                            "label": "Další údaje",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Poznámka", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 8),
                                ("route", 9),
                                ("driving_time", 10),
                                ("extra_items", 14),
                                ("note", 15),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Libovolně střídejte texty, vlastní obrázky a vlastní videa. Přidat můžete také blok Přehled autovandru.",
                verbose_name="Řaditelný obsah",
            ),
        ),
    ]
