# Generated by Django 5.0.6 on 2026-09-05 16:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadtrips", "0017_route_home_icon_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadtrippage",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 5), ("video", 7), ("trip_summary", 17)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Obrázek", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Popisek", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Zdroj", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Volitelná cílová adresa obrázku, například sdílecí odkaz https://mapy.com/s/hejunakope.",
                            "label": "Odkaz po kliknutí",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("caption", 2),
                                ("attribution", 3),
                                ("link_url", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Pro nejlepší kompatibilitu použijte formát MP4 nebo WebM.",
                            "label": "Video",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 6), ("caption", 2)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Přehled autovandru", "label": "Nadpis"},
                    ),
                    9: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {
                            "decimal_places": 1,
                            "help_text": "Celková vzdálenost celé cesty, i když ještě nejsou zveřejněné všechny dny. Nechte prázdné pro převzetí posledního vyplněného stavu ze zveřejněných dnů.",
                            "label": "Celkem najeto za celý autovandr",
                            "max_digits": 7,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Například :home: → Oslo → :home:. Zápis :home: zobrazí ikonu domova.",
                            "label": "Trasa",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Například 32 h.",
                            "label": "Čas na cestě",
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"label": "Název údaje"}),
                    13: ("wagtail.blocks.CharBlock", (), {"label": "Hodnota"}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 12), ("value", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (14,),
                        {
                            "default": [],
                            "help_text": "Například Pěšky: 60 km nebo Trajekty: 3 plavby.",
                            "label": "Další údaje",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Poznámka", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 8),
                                ("total_distance_km", 9),
                                ("route", 10),
                                ("driving_time", 11),
                                ("extra_items", 15),
                                ("note", 16),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Libovolně střídejte texty, vlastní obrázky a vlastní videa. Přidat můžete také blok Přehled autovandru.",
                verbose_name="Řaditelný obsah",
            ),
        ),
    ]
