# Generated by Django 5.0.6 on 2025-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingindexpage",
            name="subtitle",
            field=models.CharField(
                default="Programování",
                help_text="Podtitulek zobrazující se v menu",
                max_length=20,
            ),
        ),
    ]
