# Generated by Django 5.0.6 on 2024-06-21 14:13

import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipepage",
            name="backstory",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select a header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            icon="pilcrow", template="blocks/paragraph_block.html"
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="e.g. Mary Berry",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            icon="media",
                            template="blocks/embed_block.html",
                        ),
                    ),
                ],
                blank=True,
                help_text="Použij co nejmenší množství hlaviček a velkých bloků.",
            ),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select a header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Content",
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            group="Content",
                            icon="pilcrow",
                            template="blocks/paragraph_block.html",
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="e.g. Mary Berry",
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Content",
                        ),
                    ),
                    (
                        "table_block",
                        wagtail.contrib.table_block.blocks.TableBlock(group="Content"),
                    ),
                    (
                        "typed_table_block",
                        wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                            [
                                ("text", wagtail.blocks.CharBlock()),
                                ("numeric", wagtail.blocks.FloatBlock()),
                                ("rich_text", wagtail.blocks.RichTextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ],
                            group="Content",
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ],
                            group="Media",
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            group="Media",
                            help_text="Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            icon="media",
                            template="blocks/embed_block.html",
                        ),
                    ),
                    (
                        "ingredients_list",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.RichTextBlock(
                                features=["bold", "italic", "link"]
                            ),
                            group="Cooking",
                            icon="list-ol",
                            max_num=10,
                            min_num=2,
                        ),
                    ),
                    (
                        "steps_list",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "text",
                                        wagtail.blocks.RichTextBlock(
                                            features=["bold", "italic", "link"]
                                        ),
                                    ),
                                    (
                                        "difficulty",
                                        wagtail.blocks.ChoiceBlock(
                                            choices=[
                                                ("S", "Small"),
                                                ("M", "Medium"),
                                                ("L", "Large"),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                            group="Cooking",
                            icon="tasks",
                            max_num=10,
                            min_num=2,
                        ),
                    ),
                ],
                blank=True,
                help_text="Pokyny k receptu krok za krokem a další důležité informace.",
            ),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="date_published",
            field=models.DateField(
                blank=True, null=True, verbose_name="Datum publikace článku"
            ),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="introduction",
            field=models.TextField(blank=True, max_length=500, verbose_name="Úvod"),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="recipe_headline",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Dodržujte maximálně jeden řádek", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Podtitul článku"
            ),
        ),
    ]
