# Generated by Django 5.0.6 on 2024-06-22 10:03

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipepage_backstory_alter_recipepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select a header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Obsah",
                            label="Nadpis",
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            group="Obsah",
                            icon="pilcrow",
                            label="Odstavec",
                            template="blocks/paragraph_block.html",
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="e.g. Mary Berry",
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Obsah",
                            label="Citát",
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ],
                            group="Média",
                            label="Obrázek",
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            group="Média",
                            help_text="Vložte URL např. https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            icon="media",
                            label="Embed",
                            template="blocks/embed_block.html",
                        ),
                    ),
                    (
                        "difficulty",
                        wagtail.blocks.ChoiceBlock(
                            choices=[
                                ("Nízká *", "Nízká"),
                                ("Střední **", "Střední"),
                                ("Vysoká ***", "Vysoká"),
                            ],
                            group="Vaření",
                            icon="cogs",
                            label="Obtížnost",
                        ),
                    ),
                    (
                        "ingredients_list",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.RichTextBlock(
                                features=["bold", "italic", "link"]
                            ),
                            group="Vaření",
                            icon="list-ol",
                            label="Seznam ingrediencí",
                            max_num=15,
                            min_num=2,
                        ),
                    ),
                    (
                        "steps_list",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.RichTextBlock(
                                features=["bold", "italic", "link"]
                            ),
                            group="Vaření",
                            icon="tasks",
                            label="Seznam kroků",
                            max_num=15,
                            min_num=2,
                        ),
                    ),
                ],
                blank=True,
                help_text="Pokyny k receptu krok za krokem a další důležité informace.",
            ),
        ),
    ]
