# Generated by Django 5.0.6 on 2024-06-24 17:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_recipepagetag_recipepage_tags"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeindexpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Pouze režim na šířku; šířka mezi 1000px a 3000px",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="recipeindexpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Úvodní text popisující stránku"
            ),
        ),
    ]
