# Generated by Django 5.0.6 on 2025-04-19 17:43

import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_alter_recipepage_backstory_alter_recipepage_body"),
        ("wagtailcore", "0093_uploadedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="backstory",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title",
                                        label="Text nadpisu",
                                        required=True,
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Vyber velikost nadpisu"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        label="Velikost nadpisu",
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Obsah",
                            label="Nadpis",
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            group="Obsah",
                            icon="pilcrow",
                            label="Odstavec",
                            template="blocks/paragraph_block.html",
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Obrázek", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(
                                        label="Zdroj", required=False
                                    ),
                                ),
                            ],
                            group="Média",
                            label="Obrázek",
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="např. Karel Čapek",
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Obsah",
                            label="Citát",
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            group="Média",
                            help_text="Vložte URL média např. https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            icon="media",
                            label="Média",
                            template="blocks/embed_block.html",
                        ),
                    ),
                ],
                blank=True,
                help_text="Lze použít maximálně jeden nadpis, obrázek a médium.",
            ),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title",
                                        label="Text nadpisu",
                                        required=True,
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Vyber velikost nadpisu"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        label="Velikost nadpisu",
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Obsah",
                            label="Nadpis",
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            group="Obsah",
                            icon="pilcrow",
                            label="Odstavec",
                            template="blocks/paragraph_block.html",
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="např. Karel Čapek",
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Obsah",
                            label="Citát",
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Obrázek", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(
                                        label="Zdroj", required=False
                                    ),
                                ),
                            ],
                            group="Média",
                            label="Obrázek",
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            group="Média",
                            help_text="Vložte URL média např. https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            icon="media",
                            label="Média",
                            template="blocks/embed_block.html",
                        ),
                    ),
                    (
                        "difficulty",
                        wagtail.blocks.ChoiceBlock(
                            choices=[
                                ("* nízká", "Nízká"),
                                ("** střední", "Střední"),
                                ("*** vysoká", "Vysoká"),
                            ],
                            group="Vaření",
                            icon="cogs",
                            label="Obtížnost",
                            template="blocks/difficulty.html",
                        ),
                    ),
                    (
                        "ingredients_list",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.RichTextBlock(
                                features=["bold", "italic", "link"]
                            ),
                            group="Vaření",
                            icon="tasks",
                            label="Seznam ingrediencí",
                            max_num=15,
                            min_num=2,
                            template="blocks/ingredients_list_block.html",
                        ),
                    ),
                    (
                        "steps_list",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.RichTextBlock(
                                features=["bold", "italic", "link"]
                            ),
                            group="Vaření",
                            icon="list-ol",
                            label="Seznam kroků",
                            max_num=15,
                            min_num=2,
                            template="blocks/steps_list_block.html",
                        ),
                    ),
                ],
                blank=True,
                help_text="Pokyny k receptu krok za krokem a další důležité informace.",
            ),
        ),
    ]
