# Generated by Django 5.0.6 on 2025-04-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipecategorypage_alter_recipepage_backstory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipepage",
            name="category",
        ),
    ]
