# Generated by Django 5.0.6 on 2025-04-19 18:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_remove_recipepage_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeCategory",
        ),
        migrations.AlterField(
            model_name="recipecategorypage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Úvodní text popisující kategorii"
            ),
        ),
    ]
