# Generated by Django 5.0.6 on 2025-04-19 22:11

import datetime
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_delete_recipecategory_alter_recipecategorypage_intro"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipepage",
            name="date_published",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Datum publikace receptu"
            ),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Podtitul receptu, zobrazí se na stránce s receptem",
            ),
        ),
        migrations.CreateModel(
            name="BlogPageGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("caption", models.CharField(blank=True, max_length=250)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="recipes.recipepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
