# Generated by Django 5.0.6 on 2025-04-21 12:00

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0018_remove_recipepage_linked_page_alter_recipepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_text",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title",
                                        label="Text nadpisu",
                                        required=True,
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Vyber velikost nadpisu"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        label="Velikost nadpisu",
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Obsah",
                            label="Nadpis",
                        ),
                    ),
                    (
                        "paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            group="Obsah",
                            icon="pilcrow",
                            label="Odstavec",
                            template="blocks/paragraph_block.html",
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.TextBlock(label="Citát")),
                                (
                                    "attribute_name",
                                    wagtail.blocks.CharBlock(
                                        blank=True,
                                        label="např. Karel Čapek",
                                        required=False,
                                    ),
                                ),
                            ],
                            group="Obsah",
                            label="Citát",
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Obrázek", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Popisek", required=False
                                    ),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(
                                        label="Zdroj", required=False
                                    ),
                                ),
                            ],
                            group="Média",
                            label="Obrázek",
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            group="Média",
                            help_text="Vložte URL média např. https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            icon="media",
                            label="Média",
                            template="blocks/embed_block.html",
                        ),
                    ),
                    (
                        "difficulty",
                        wagtail.blocks.ChoiceBlock(
                            choices=[
                                ("* nízká", "Nízká"),
                                ("** střední", "Střední"),
                                ("*** vysoká", "Vysoká"),
                            ],
                            group="Vaření",
                            icon="cogs",
                            label="Obtížnost",
                            template="blocks/difficulty.html",
                        ),
                    ),
                    (
                        "ingredients_list",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Seznam ingrediencí:",
                                        help_text="Tento nadpis se zobrazí nad seznamem ingrediencí",
                                        label="Nadpis bloku s ingrediencemi",
                                        required=False,
                                    ),
                                ),
                                (
                                    "ingredients_list",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.RichTextBlock(
                                            features=["bold", "italic", "link"]
                                        ),
                                        label="Seznam ingrediencí",
                                        max_num=15,
                                        min_num=2,
                                    ),
                                ),
                            ],
                            group="Vaření",
                        ),
                    ),
                    (
                        "steps_list",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Seznam kroků:",
                                        help_text="Tento nadpis se zobrazí nad seznamem kroků",
                                        label="Nadpis bloku s kroky receptu",
                                        required=False,
                                    ),
                                ),
                                (
                                    "steps_list",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.RichTextBlock(
                                            features=["bold", "italic", "link"]
                                        ),
                                        label="Seznam kroků",
                                        max_num=15,
                                        min_num=2,
                                    ),
                                ),
                            ],
                            group="Vaření",
                        ),
                    ),
                    (
                        "links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="Přílohy:",
                                        help_text="Tento nadpis se zobrazí nad interními odkazy stránek s přílohami",
                                        label="Nadpis bloku s přílohami",
                                        required=False,
                                    ),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.PageChooserBlock(),
                                        label="Odkazy",
                                    ),
                                ),
                            ],
                            group="Vaření",
                        ),
                    ),
                ],
                blank=True,
                help_text="Pokyny k receptu krok za krokem a další důležité informace.",
            ),
        ),
    ]
