# Generated by Django 5.0.6 on 2025-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0020_alter_recipepage_body_alter_recipepage_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipepage",
            name="introduction",
            field=models.TextField(blank=True, max_length=300, verbose_name="Úvod"),
        ),
    ]
