# Generated by Django 5.0.6 on 2025-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_alter_recipepage_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeindexpage",
            name="subtitle",
            field=models.CharField(
                default="Recepty",
                help_text="Podtitulek zobrazující se v menu",
                max_length=20,
            ),
        ),
    ]
