# Generated by Django 5.0.6 on 2025-04-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_recipeindexpage_subtitle"),
        ("recipes", "0022_recipeindexpage_subtitle"),
    ]

    operations = []
