# Generated by Django 5.0.4 on 2024-05-06 19:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage_title_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='title_background_image',
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='image',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
