# Generated by Django 5.0.4 on 2024-05-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogindexpage_title_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='image',
        ),
    ]
