# Generated by Django 5.0.4 on 2024-05-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='teaser',
            field=models.TextField(blank=True, null=True, verbose_name='Teaser'),
        ),
    ]
