# Generated by Django 5.0.4 on 2024-05-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_teaser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='teaser',
        ),
    ]
