# Generated by Django 5.0.4 on 2024-05-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpage_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_nr',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
