# Generated by Django 5.0.4 on 2024-05-15 20:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpage_blog_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blog_nr',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Číslo blogu'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(verbose_name='Datum publikace'),
        ),
    ]
