# Generated by Django 5.0.6 on 2024-05-17 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_blogtagindexpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Datum publikace"
            ),
        ),
    ]
