# Generated by Django 5.0.6 on 2024-06-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_blogindexpage_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogTagIndexPage",
        ),
    ]
