# Generated by Django 5.0.6 on 2025-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_blogindexpage_image_alter_blogindexpage_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="subtitle",
            field=models.CharField(
                default="Blog",
                help_text="Podtitulek zobrazující se v menu",
                max_length=20,
            ),
        ),
    ]
