# Generated by Django 5.0.6 on 2024-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0003_cookbookindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookbookpage",
            name="blog_nr",
            field=models.PositiveIntegerField(
                null=True, unique=True, verbose_name="Číslo blogu"
            ),
        ),
    ]
